HelloWorld/HelloWorld/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('gym/', include('gym.urls')),
    path('', include('gym.urls')),
]

HelloWorld/gym/urls.py
from django.urls import path

from . import views

app_name = 'gym'

urlpatterns = [
    # ex: http://localhost:8000/gym/
    path('', views.index, name='index'),

    # ex: http://localhost:8000/gym/login/
    path('login/', views.login, name='login'),

    # ex: http://localhost:8000/gym/logout/
    path('logout/', views.logout, name='logout'),

    # ex: http://localhost:8000/gym/register/
    path('register/', views.register, name='register'),

    # ex: http://localhost:8000/gym/mygxin/
    path('mygxin/', views.mygxin, name='mygxin'),

    # ex: http://localhost:8000/gym/mygrxx/
    path('mygrxx/', views.mygrxx, name='mygrxx'),

    # ex: http://localhost:8000/gym/myprod/
    path('myprod/', views.myprod, name='myprod'),

    # ex: http://localhost:8000/gym/myorderq/
    path('myorderq/', views.myorderq, name='myorderq'),

    # ex: http://localhost:8000/gym/remima/
    path('remima/', views.remima, name='remima'),

    # ex: http://localhost:8000/gym/showcourse/
    path('showcourse/', views.showcourse, name='showcourse'),

    # ex: http://localhost:8000/gym/orderxq/5/
    path('orderxq/<int:order_id>', views.orderxq, name='orderxq'),

    # 测试用
    path('showcoach/', views.showcoach, name='showcoach'),
    path('ok/', views.ok, name='ok'),
    path('order/', views.order, name='order'),
    path('locker/', views.locker, name='locker'),
    path('courseorder/', views.courseorder, name='courseorder'),

]

HelloWorld/gym/models.py
from django.db import models

# Create your models here.
class Gender(models.TextChoices):
    MAN = '男'
    WOMAN = '女'
    UNKOWN = '未知'


# 教练
class Coach(models.Model):
    name = models.CharField(max_length=200)
    tel = models.CharField(max_length=11, unique=True)
    gender = models.CharField(max_length=4,
                            choices=Gender.choices,
                            default=Gender.UNKOWN)
    birthday = models.DateField(auto_now=True)
    info = models.TextField(default='这里空荡荡的，什么也没有。')

    def __str__(self):
        return self.name


#用户
class User(models.Model):
    name = models.CharField(max_length=200, default='普通用户')
    tel = models.CharField(max_length=11, unique=True)
    gender = models.CharField(max_length=4,
                            choices=Gender.choices,
                            default=Gender.UNKOWN)
    birthday = models.DateField(auto_now=True)
    regtime = models.DateField(auto_now=True)
    isvip = models.BooleanField(default=False)
    vipstart = models.DateTimeField(auto_now=True)
    vipend = models.DateTimeField(auto_now=True)
    pwd = models.CharField(max_length=20)

    def __str__(self):
        return self.name


# 课程
class Course(models.Model):
    coach = models.ForeignKey(Coach, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    start = models.DateField()
    end = models.DateField()
    maxnum = models.IntegerField()
    info = models.TextField()

    def __str__(self):
        return self.name

#健康报告
class PhyTest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coach= models.ForeignKey(Coach, on_delete=models.CASCADE)
    time = models.DateTimeField()
    height = models.FloatField()
    weight = models.FloatField()
    muscle = models.FloatField()
    fat = models.FloatField()
    water = models.FloatField()

#储物柜
class Locker(models.Model):
    location = models.CharField(max_length=200)
    isavailable = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.location

#课程订单
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.IntegerField()
    time = models.DateTimeField(auto_now=True)
    comment = models.TextField()
    star = models.IntegerField()

#留言
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)
    msg = models.TextField()

HelloWorld/gym/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import User, Coach, Course, Locker, PhyTest, Order, Message


def index(request):
    latest_course_list = Course.objects.all()[:12]
    context = {'latest_course_list': latest_course_list}
    return render(request, 'gym/index.html', context)

def login(request):
    context = {}
    if request.method == 'POST':
        # 获取到用户提交的用户名密码
        # 1）校验成功，告知登陆成功
        # 2）校验失败，返回登陆页面
        tel = request.POST.get('tel')
        pwd = request.POST.get('pwd')
        if User.objects.filter(tel=tel, pwd=pwd):
            request.session['tel'] = tel
            latest_course_list = Course.objects.all()[:12]
            context['latest_course_list'] = latest_course_list
            return redirect(reverse('gym:index'), latest_course_list=latest_course_list)
        else:
            context['msg'] = '用户名或密码错误'
    return render(request, 'gym/login.html', context)

def logout(request):
    latest_course_list = Course.objects.all()[:12]
    context = {'latest_course_list': latest_course_list}
    request.session.flush()
    return redirect(reverse('gym:index'))

def register(request):
    context = {}
    if request.method == 'POST':
        # 获取到用户提交的用户名密码
        # 1）校验成功，告知注册成功
        # 2）校验失败，返回注册页面
        tel = request.POST.get('tel')
        pwd = request.POST.get('pwd')
        if User.objects.filter(tel=tel):
            context['msg'] = '该用户已被注册'
        else:
            newuser = User(tel=tel, pwd=pwd)
            newuser.save()
            context['msg'] = '注册成功'
    return render(request, 'gym/register.html', context)

def mygxin(request):
    tel = request.session.get('tel')
    user = User.objects.get(tel=tel)
    context = {'user': user}
    return render(request, 'gym/mygxin.html', context)

def mygrxx(request):
    tel = request.session.get('tel')
    if request.method == 'POST':
        name = request.POST.get('name')
        gender = request.POST.get('gender')
        User.objects.filter(tel=tel).update(name=name)
        User.objects.filter(tel=tel).update(gender=gender)
    user = User.objects.get(tel=tel)
    context = {'user': user}
    return render(request, 'gym/mygrxx.html', context)

def myorderq(request):
    tel = request.session.get('tel')
    user = User.objects.get(tel=tel)
    context = {'user': user}
    order_list = Order.objects.filter(user_id=user.id)
    for order in order_list:
        order.course_id = Course.objects.get(id=order.course_id)
    context['order_list'] = order_list
    return render(request, 'gym/myorderq.html', context)

def myprod(request):
    tel = request.session.get('tel')
    user = User.objects.get(tel=tel)
    context = {'user': user}
    order_list = Order.objects.filter(user_id=user.id)
    for order in order_list:
        order.course_id = Course.objects.get(id=order.course_id)
        context['fake_comment'] = order.comment
    context['order_list'] = order_list
    if request.method == 'POST':
        comment = request.POST.get('comment')
        print(comment)
        Order.objects.filter(user_id=user.id).update(comment=comment)
        Order.objects.filter(user_id=user.id).update(star=5)
        Order.objects.filter(user_id=user.id).update(status=1)
<<<<<<< HEAD
    print(1111111111111111111111111)
=======
>>>>>>> newbranch
    return render(request, 'gym/myprod.html', context)

def remima(request):
    tel = request.session.get('tel')
    user = User.objects.get(tel=tel)
    context = {'user': user}
    if request.method == 'POST':
        pwd = request.POST.get('pwd')
        new_pwd = request.POST.get('new_pwd')
        new_pwd_1 = request.POST.get('anew_pwd')
        print(new_pwd, new_pwd_1)
        if User.objects.filter(tel=tel, pwd=pwd):
            if new_pwd == new_pwd_1:
                User.objects.filter(tel=tel, pwd=pwd).update(pwd=new_pwd)
                context['msg'] = '修改成功'
            else:
                context['msg'] = '两次密码不匹配'
        else:
            context['msg'] = '原密码错误'
    return render(request, 'gym/remima.html', context)

def showcourse(request):
    tel = request.session.get('tel')
<<<<<<< HEAD
    user = User.objects.get(tel=tel)
    context = {'user': user}
    course_list = Course.objects.all()
    context['course_list'] = course_list
=======
    context = {}
    course_list = Course.objects.all()
    coach_list = Coach.objects.all()
    context['course_list'] = course_list
    context['coach_list'] = coach_list
    if request.method == 'POST':
        user = User.objects.get(tel=tel)
        course_id = request.POST.get('course_id')
        context['user'] = user
        user_id = user.id
        status = 0
        Order.objects.create(user_id=user_id, course_id=course_id, status=status, star=5)
        return render(request, 'gym/ok.html', context)
>>>>>>> newbranch
    return render(request, 'gym/showcourse.html', context)

def orderxq(request, order_id):
    tel = request.session.get('tel')
    user = User.objects.get(tel=tel)
    context = {'user': user}
    order = Order.objects.get(id=order_id)
    course = Course.objects.get(id=order.course_id)
    coach = Coach.objects.get(id=course.coach_id)
    context['order'] = order
    context['course'] = course
    context['coach'] = coach
    return render(request, 'gym/orderxq.html', context)

#支付成功
def ok(request):
    return render(request,'gym/ok.html')
<<<<<<< HEAD
=======

>>>>>>> newbranch
#展示教练
def showcoach(request):
    tel = request.session.get('tel')
    context = {}
    coach_list = Coach.objects.all()
    context['coach_list'] = coach_list
    return render(request,'gym/showcoach.html', context)

#订单
def order(request):
    return render(request,'gym/order.html')


#储物柜
def locker(request):
<<<<<<< HEAD
    return render(request,'gym/locker.html')
=======
    tel = request.session.get('tel')
    context = {}
    locker_list = Locker.objects.all()
    context['locker_list'] = locker_list
    return render(request,'gym/locker.html', context)

#课程预约
def courseorder(request):
    tel = request.session.get('tel')
    context = {}
    message_list = Message.objects.all()
    context['message_list'] = message_list
    if request.method == 'POST':
        user = User.objects.get(tel=tel)
        context['user'] = user
        msg = request.POST.get('msg')
        Message.objects.create(user_id=user.id, msg=msg)
    return render(request,'gym/courseorder.html', context)
>>>>>>> newbranch

HelloWorld/gym/templates/gym/courseorder.html
{% load static %}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8" />
		<title>储物柜租用</title>
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/public.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/proList.css' %}"/>
	</head>
	<body>
		<!------------------------------head------------------------------>
		<div class="head">
			<div class="wrapper clearfix">
				<div class="clearfix" id="top">

					<h1 class="fl"><a href="{% url 'gym:index' %}"><img src="{% static 'gym/style/images/1logo.png' %}"/></a></h1>
					<div class="fr clearfix" id="top1">
                        {% if request.session.tel %}
                            <div class="btn fl clearfix">
							    <a href="{% url 'gym:mygxin' %}"><img src="{% static 'gym/style/images/grzx.png' %}"/></a>
						    </div>
                            {% else %}
                            <p class="fl">
                                <a href="{% url 'gym:login' %}" id="login">登录</a>
                                <a href="{% url 'gym:register' %}" id="reg">注册</a>
                            </p>
                        {% endif %}
					</div>
				</div>


				<ul class="clearfix" id="bott">
					<li><a href="{% url 'gym:index' %}">首页</a></li>
					<li>
						<a href="{% url 'gym:showcourse' %}">所有课程</a>
						<div class="sList">
							<div class="wrapper  clearfix">
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav1.png' %}"/></dt>
										<dd>现代瑜伽</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav2.png' %}"/></dt>
										<dd>动感单车</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav3.png' %}"/></dt>
										<dd>有氧长跑</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav4.png' %}"/></dt>
										<dd>力量训练</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav5.png' %}"/></dt>
										<dd>身体激活</dd>
									</dl>
								</a>
							</div>
						</div>
					</li>
                    <a href="paint.html">
					<li>
                        <a href="{% url 'gym:index' %}">最新通知</a>
						<div class="sList2">
							<div class="clearfix">
								<a href="proList.html">活动相关</a>
								<a href="vase_proList.html">通知相关</a>
							</div>
						</div>
					</li>
					<li>
						<a href="{% url 'gym:showcoach' %}">明星教练</a>

					</li>
					<!--以下展示应当在用户登录后出现-->
					{% if request.session.tel %}
					<li><a href="{% url 'gym:locker' %}" >储物柜租用</a></li>
					<li><a href="{% url 'gym:courseorder' %}" >课程预约</a></li>
					{% endif %}

				</ul>
			</div>
		</div>
		<!-------------------------banner--------------------------->
		<div class="banner">
			<a href="#"><img src="{% static 'gym/style/images/banner1.png' %}"/></a>
		</div>

		<!-----------------address------------------------------->
		<div class="address">
			<div class="wrapper">
				<a href="{% url 'gym:index' %}">首页</a>
				<span>/</span>
				<a href="{% url 'gym:locker' %}" class="on">留言板</a>
			</div>
        </div>
        
        <div class="wrapper">
            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="msg" style="font-size: 15px;" placeholder="请输入想要说的话">
                <input type="submit" style="background-color: #4CAF50;font-size: 15px;" value="留言">
            </form>
        </div>
<br>
		<!----------------proList------------------------->
		<ul class="wrapper" style="
    {#border-radius: 25px;#}
    border: 2px solid #8AC007;
    width: 70%;
    height: 100%;
    font-size: 15px;
    line-height:2.4;
}">
            {% for message in message_list %}
            <li>
                <div><p>用户编号：{{ message.user_id }}</p></div>
                <div><p>留言时间：{{ message.time }}</p></div>
                <div><p>{{ message.msg }}</p></div>
            <div><p>       ---------------------------         </p></div>
            </li>
            {% endfor %}
		</ul>
		<!----------------mask------------------->
		<div class="mask"></div>
		<!--返回顶部-->
		<div class="gotop">
			<a href="#" class="dh">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt2.png' %}"/></dt>
				<dd>联系<br />客服</dd>
			</dl>
			</a>
			<a href="{% url 'gym:mygrxx' %}">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt3.png' %}"/></dt>
				<dd>个人<br />中心</dd>
			</dl>
			</a>
			<a href="#" class="toptop" style="display: none;">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt4.png' %}"/></dt>
				<dd>返回<br />顶部</dd>
			</dl>
			</a>
			<p>400-800-8200</p>
		</div>
<!--footer-->
		<div class="footer">
			<p class="dibu">海事杠铃  &copy;2020-2077海事杠铃开发小组版权所有<br />
		</div>
		<script src="{% static 'gym/style/js/jquery-1.12.4.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/public.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/nav.js' %}" type="text/javascript" charset="utf-8"></script>
	</body>
</html>

HelloWorld/gym/templates/gym/index.html
{% load static %}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8" />
		<title>海事杠铃健身房</title>
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/public.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/index.css' %}" />
	</head>
	<body>
		<!------------------------------head------------------------------>
		<div class="head">
			<div class="wrapper clearfix">
				<div class="clearfix" id="top">
					<h1 class="fl"><a href="{% url 'gym:index' %}"><img src="{% static 'gym/style/images/1logo.png' %}"/></a></h1>
					<div class="fr clearfix" id="top1">
						{% if request.session.tel %}
						<div class="btn fl clearfix">
							<a href="{% url 'gym:mygxin' %}"><img src="{% static 'gym/style/images/grzx.png' %}"/></a>
						</div>
						{% else %}
						<p class="fl">
							<a href="{% url 'gym:login' %}" id="login">登录</a>
							<a href="{% url 'gym:register' %}" id="reg">注册</a>
						</p>
						{% endif %}
					</div>
				</div>


				<ul class="clearfix" id="bott">
					<li><a href="{% url 'gym:index' %}">首页</a></li>
					<li>
						<a href="{% url 'gym:showcourse' %}">所有课程</a>
						<div class="sList">
							<div class="wrapper  clearfix">
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav1.png' %}"/></dt>
										<dd>现代瑜伽</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav2.png' %}"/></dt>
										<dd>动感单车</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav3.png' %}"/></dt>
										<dd>有氧长跑</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav4.png' %}"/></dt>
										<dd>力量训练</dd>
									</dl>
								</a>
								<a href="paint.html">
									<dl>
										<dt><img src="{% static 'gym/style/images/nav5.png' %}"/></dt>
										<dd>身体激活</dd>
									</dl>
								</a>
							</div>
						</div>
					</li>
					<li>
						<a href="{% url 'gym:index' %}">最新通知</a>
						<div class="sList2">
							<div class="clearfix">
								<a>活动相关</a>
								<a>通知相关</a>
							</div>
						</div>
					</li>
					<li>
						<a href="{% url 'gym:showcoach' %}">明星教练</a>
					</li>
					<!--以下展示应当在用户登录后出现-->
					{% if request.session.tel %}
					<li><a href="{% url 'gym:locker' %}" >储物柜租用</a></li>
					<li><a href="{% url 'gym:courseorder' %}" >课程预约</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
		<!-------------------------banner--------------------------->
		<div class="block_home_slider">
			<div id="home_slider" class="flexslider">
				<ul class="slides">
					<li>
						<div class="slide">
							<img src="{% static 'gym/style/images/banner2 (2).jpg' %}"/>
						</div>
					</li>
					<li>
						<div class="slide">
							<img src="{% static 'gym/style/images/banner1 (2).jpg' %}"/>
						</div>
					</li>
				</ul>
			</div>
		</div>

		
		<!--右侧导航栏-->
		<div class="gotop">
			<a href="#" class="dh">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt2.png' %}"/></dt>
				<dd>联系<br />客服</dd>
			</dl>
			</a>
			<a href="{% url 'gym:mygxin' %}">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt3.png' %}"/></dt>
				<dd>个人<br />中心</dd>
			</dl>
			</a>
			<a href="#" class="toptop" style="display: none">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt4.png' %}"/></dt>
				<dd>返回<br />顶部</dd>
			</dl>
			</a>
			<p>179-217-1227</p>
		</div>
		
		<!-------------------login-------------------------->
		<!--footer-->
		<div class="footer">
			<p class="dibu">海事杠铃  &copy;2020-2077海事杠铃开发小组版权所有<br />
		</div>
		<script src="{% static 'gym/style/js/jquery-1.12.4.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/public.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/nav.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/jquery.flexslider-min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script type="text/javascript">
			$(function() {
				$('#home_slider').flexslider({
					animation: 'slide',
					controlNav: true,
					directionNav: true,
					animationLoop: true,
					slideshow: true,
					slideshowSpeed:2000,
					useCSS: false
				});
			});
		</script>
		
		
	</body>
</html>

HelloWorld/gym/templates/gym/myorderq.html
{% load static %}
<!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="utf-8" />
		<title>个人中心</title>
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/public.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'gym/style/css/myorder.css' %}" />
	</head>
	<body>
		<!------------------------------head------------------------------>
		<div class="head ding">
			<div class="wrapper clearfix">
				<div class="clearfix" id="top">
					<h1 class="fl"><a href="{% url 'gym:index' %}"><img src="{% static 'gym/style/images/1logo.png' %}"/></a></h1>
					<div class="fr clearfix" id="top1">
						{% if request.session.tel %}
						<p class="fl">
							<a href="{% url 'gym:login' %}" id="login">登录</a>
							<a href="{% url 'gym:register' %}" id="reg">注册</a>
						</p>
						{% endif %}
						<form action="#" method="get" class="fl">
							<input type="text" placeholder="搜索" />
							<input type="button" />
						</form>
						<div class="btn fl clearfix">
							<a href="{% url 'gym:mygxin' %}"><img src="{% static 'gym/style/images/grzx.png' %}"/></a>
							<a href="#" class="er1"><img src="{% static 'gym/style/images/ewm.png' %}"/></a>
							<p><a href="#"><img src="{% static 'gym/style/images/smewm.png' %}"/></a></p>
						</div>
					</div>
				</div>
				<ul class="clearfix" id="bott">
				</ul>
			</div>
		</div>
		<!------------------------------idea------------------------------>
		<div class="address mt">
			<div class="wrapper clearfix">
				<a href="#" class="fl">首页</a>
				<span>/</span>
				<a href="{% url 'gym:mygxin' %}">个人中心</a>
				<span>/</span>
				<a href="{% url 'gym:myorderq' %}" class="on">我的订单</a>
			</div>
		</div>

		<!------------------------------Bott------------------------------>
		<div class="Bott">
			<div class="wrapper clearfix">
				<div class="zuo fl">
					<h3>
						<a href="#"><img src="{% static 'gym/style/images/tx.png' %}"/></a>
						<p class="clearfix"><span class="fl">{{ user.name }}</span><span class="fr"><a href="{% url 'gym:logout' %}">[退出登录]</a></span></p>
					</h3>
					<div>
						<h4>我的交易</h4>
						<ul>
							<li><a href="{% url 'gym:myorderq' %}">我的课程</a></li>
							<li><a href="{% url 'gym:myprod' %}">课程评价</a></li>
						</ul>
						<h4>个人中心</h4>
						<ul>
							<li><a href="{% url 'gym:mygxin' %}">我的中心</a></li>
							<li><a href="{% url 'gym:mygrxx' %}">健康报告</a></li>

						</ul>
						<h4>账户管理</h4>
						<ul>
							<li  class="on"><a href="{% url 'gym:mygrxx' %}">个人信息</a></li>
							<li><a href="{% url 'gym:remima' %}">修改密码</a></li>
						</ul>
					</div>
				</div>
				<div class="you fl">
					<div class="my clearfix">
						<h2 class="fl">我的订单</h2>
					</div>
					<div class="dlist clearfix">
						<ul class="fl clearfix" id="wa">
							<li class="on"><a href="#2">全部已购课程</a></li>
							<li><a href="#2">待开课</a></li>
							<li><a href="#2l">已开课</a></li>
							<li><a href="#2">已停课</a></li>
						</ul>
						<form action="#" method="get" class="fr clearfix">
							<input type="text" name="" id="" value="" placeholder="请输入商品名称、订单号" />
							<input type="button" name="" id="" value="" />
						</form>
					</div>
					{% for order in order_list %}
					<div class="dkuang">
						<p class="one">已开课</p>
						<div class="word clearfix">
							<ul class="fl clearfix">
								<li>{{ order.time }}</li>
								<li>{{ user.name }}</li>
								<li>订单号:{{ order.id }}</li>
								<li>在线支付</li>
							</ul>
							<p class="fr">订单金额：<span>{{ order.course_id.price }}</span>元</p>
						</div>
						<div class="shohou clearfix">
							<a href="#" class="fl"><img src="{% static 'gym/style/images/g1.png' %}"/></a>
							<p class="fl"><a href="#">{{ order.course_id.name }}</a><a href="#">¥{{ order.course_id.price }}×1</a></p>
							<p class="fr">
								<a href="{% url 'gym:myprod' %}">待评价</a>
								<a href="{% url 'gym:orderxq' order.id %}">订单详情</a>
							</p>
						</div>
					</div>
					{% endfor %}
<<<<<<< HEAD

=======
>>>>>>> newbranch
					<div class="fenye clearfix">
						<a href="#"><img src="{% static 'gym/style/images/zuo.jpg' %}"/></a>
						<a href="#">1</a>
						<a href="#"><img src="{% static 'gym/style/images/you.jpg' %}"/></a>
					</div>
				</div>
			</div>
		</div>
		<!--返回顶部-->
		<div class="gotop">
			<a href="#" class="dh">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt2.png' %}"/></dt>
				<dd>联系<br />客服</dd>
			</dl>
			</a>
			<a href="{% url 'gym:mygxin' %}">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt3.png' %}"/></dt>
				<dd>个人<br />中心</dd>
			</dl>
			</a>
			<a href="#" class="toptop" style="display: none">
			<dl>
				<dt><img src="{% static 'gym/style/images/gt4.png' %}"/></dt>
				<dd>返回<br />顶部</dd>
			</dl>
			</a>
			<p>400-800-8200</p>
		</div>
		<!--footer-->
        <div class="footer">
			<p class="dibu">海事杠铃  &copy;2020-2077海事杠铃开发小组版权所有<br />
		</div>
		<script src="{% static 'gym/style/js/jquery-1.12.4.min.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/public.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'gym/style/js/user.js' %}" type="text/javascript" charset="utf-8"></script>
	</body>
</html>